version: "3"
services:
  secretary:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    environment:
      - FLASK_SECRET_KEY=your_random_secret_key_please_change_this
      - DATABASE_PATH=/data/secretary.db
    env_file:
      - .env
    restart: always
