version: "3"
services:
  tweetanalyst:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    environment:
      - FLASK_SECRET_KEY=your_random_secret_key_please_change_this
      - DATABASE_PATH=/data/tweetanalyst.db
      - LOG_DIR=/data/logs
      - FIRST_LOGIN=true
    env_file:
      - .env
    restart: always
