version: 1

# Apprise URLs配置
# 每个URL对应一个通知服务
# 可以为URL指定标签，用于筛选通知目标

# 示例配置
urls:
  # 已删除企业微信机器人配置

  # Telegram机器人示例
  - url: tgram://$TELEGRAM_BOT_TOKEN/$TELEGRAM_CHAT_ID
    tag: all

  # Discord示例
  - url: discord://$DISCORD_WEBHOOK_ID/$DISCORD_WEBHOOK_TOKEN
    tag: all

  # 邮件示例
  - url: mailto://$EMAIL_USER:$EMAIL_PASSWORD@$EMAIL_SMTP_SERVER?to=$TO_EMAIL
    tag: important
