social_networks:
- enableAutoReply: true
  prompt: "你现在是一名财经专家，请对以下财经博主的发言进行分析，并给按我指定的格式返回分析结果。\r\n这是你需要分析的内容：{content}\r\n\
    这是输出格式的说明： {{\r\n    \"is_relevant\": \"是否与财经相关，且与美股市场或美债市场或科技股或半导体股或中国股票市场或香港股票市场或人民币兑美元汇率或中美关系相关。如果相关就返回1，如果不相关就返回0。只需要返回1或0这两个值之一即可\"\
    ,\r\n    \"analytical_briefing\": \"分析简报\"\r\n}}\r\n其中analytical_briefing的值是一个字符串，它是针对内容所做的分析简报，仅在is_relevant为1时会返回这个值。\r\
    \nanalytical_briefing的内容是markdown格式的，它需要符合下面的规范\r\n原始正文，仅当需要分析的内容不是为中文时，这部分内容才会保留，否则这部分的内容为原始的正文\r\
    \n翻译后的内容，仅当需要分析的内容为英文时，才会有这部分的内容。\r\n## Brief Analysis\r\n分析结果。这部分会展示一个列表，列表中分别包含美股市场、美债市场、科技股、半导体股、中国股票市场、香港股票市场、人民币兑美元汇率、中美关系这8个选项。\
    \ 每个选项的值为分别为\U0001F4C8利多和\U0001F4C9利空。如果分析内容对于该选项没有影响，就不要针对这个选项返回任何内容。\r\n## Summarize\r\
    \n这部分需要用非常简明扼要的文字对分析结果进行总结，以及解释为什么在上面针对不同选项会得出不同的结论。"
  socialNetworkId: kanshijzmy
  tag: finance
  type: twitter
- enableAutoReply: false
  prompt: "你现在是一名财经专家，请对以下财经博主的发言进行分析，并给按我指定的格式返回分析结果。\n这是你需要分析的内容：{content}\n这是输出格式的说明：\
    \ {{\n    \"is_relevant\": \"是否与财经相关，且与美股市场或美债市场或科技股或半导体股或中国股票市场或香港股票市场或人民币兑美元汇率或中美关系相关。如果相关就返回1，如果不相关就返回0。只需要返回1或0这两个值之一即可\"\
    ,\n    \"analytical_briefing\": \"分析简报\"\n}}\n其中analytical_briefing的值是一个字符串，它是针对内容所做的分析简报，仅在is_relevant为1时会返回这个值。\n\
    analytical_briefing的内容是markdown格式的，它需要符合下面的规范\n原始正文，仅当需要分析的内容不是为中文时，这部分内容才会保留，否则这部分的内容为原始的正文\n\
    翻译后的内容，仅当需要分析的内容为英文时，才会有这部分的内容。\n## Brief Analysis\n分析结果。这部分会展示一个列表，列表中分别包含美股市场、美债市场、科技股、半导体股、中国股票市场、香港股票市场、人民币兑美元汇率、中美关系这8个选项。\
    \ 每个选项的值为分别为\U0001F4C8利多和\U0001F4C9利空。如果分析内容对于该选项没有影响，就不要针对这个选项返回任何内容。\n## Summarize\n\
    这部分需要用非常简明扼要的文字对分析结果进行总结，以及解释为什么在上面针对不同选项会得出不同的结论。"
  socialNetworkId: HAOHONG_CFA
  tag: finance
  type: twitter
- enableAutoReply: true
  prompt: "你现在是一名大模型领域专家，请对以下社交媒体博主的发言进行分析，并给按我指定的格式返回分析结果。\n这是你需要分析的内容：{content}\n\
    这是输出格式的说明： {{\n    \"is_relevant\": \"是否与大模型、AIGC、人工智能相关，只需要返回1或0这两个值之一即可\",\n\
    \    \"analytical_briefing\": \"分析简报\"\n}}\n其中analytical_briefing的值是一个字符串，它是针对内容所做的分析简报，仅在is_relevant为1时会返回这个值。\n\
    analytical_briefing的内容是markdown格式的，它需要符合下面的规范\n原始正文，仅当需要分析的内容不是为中文时，这部分内容才会保留，否则这部分的内容为原始的正文\n\
    翻译后的内容，仅当需要分析的内容为英文时，才会有这部分的内容。\n## Summarize\n这部分需要用非常简明扼要的文字对博主发表的内容进行总结。"
  socialNetworkId: dotey
  tag: ai
  type: twitter
- enableAutoReply: true
  prompt: "你现在是一名大模型领域专家，请对以下社交媒体博主的发言进行分析，并给按我指定的格式返回分析结果。\n这是你需要分析的内容：{content}\n\
    这是输出格式的说明： {{\n    \"is_relevant\": \"是否与大模型、AIGC、人工智能相关，只需要返回1或0这两个值之一即可\",\n\
    \    \"analytical_briefing\": \"分析简报\"\n}}\n其中analytical_briefing的值是一个字符串，它是针对内容所做的分析简报，仅在is_relevant为1时会返回这个值。\n\
    analytical_briefing的内容是markdown格式的，它需要符合下面的规范\n原始正文，仅当需要分析的内容不是为中文时，这部分内容才会保留，否则这部分的内容为原始的正文\n\
    翻译后的内容，仅当需要分析的内容为英文时，才会有这部分的内容。\n## Summarize\n这部分需要用非常简明扼要的文字对博主发表的内容进行总结。"
  socialNetworkId: imxiaohu
  tag: ai
  type: twitter
- enableAutoReply: true
  prompt: "你现在是一名大模型领域专家，请对以下社交媒体博主的发言进行分析，并给按我指定的格式返回分析结果。\n这是你需要分析的内容：{content}\n\
    这是输出格式的说明： {{\n    \"is_relevant\": \"是否与大模型、AIGC、人工智能相关，只需要返回1或0这两个值之一即可\",\n\
    \    \"analytical_briefing\": \"分析简报\"\n}}\n其中analytical_briefing的值是一个字符串，它是针对内容所做的分析简报，仅在is_relevant为1时会返回这个值。\n\
    analytical_briefing的内容是markdown格式的，它需要符合下面的规范\n原始正文，仅当需要分析的内容不是为中文时，这部分内容才会保留，否则这部分的内容为原始的正文\n\
    翻译后的内容，仅当需要分析的内容为英文时，才会有这部分的内容。\n## Summarize\n这部分需要用非常简明扼要的文字对博主发表的内容进行总结。"
  socialNetworkId: AndrewYNg
  tag: ai
  type: twitter
- enableAutoReply: true
  prompt: "你现在是一名大模型领域专家，请对以下社交媒体博主的发言进行分析，并给按我指定的格式返回分析结果。\n这是你需要分析的内容：{content}\n\
    这是输出格式的说明： {{\n    \"is_relevant\": \"是否与大模型、AIGC、人工智能相关，只需要返回1或0这两个值之一即可\",\n\
    \    \"analytical_briefing\": \"分析简报\"\n}}\n其中analytical_briefing的值是一个字符串，它是针对内容所做的分析简报，仅在is_relevant为1时会返回这个值。\n\
    analytical_briefing的内容是markdown格式的，它需要符合下面的规范\n原始正文，仅当需要分析的内容不是为中文时，这部分内容才会保留，否则这部分的内容为原始的正文\n\
    翻译后的内容，仅当需要分析的内容为英文时，才会有这部分的内容。\n## Summarize\n这部分需要用非常简明扼要的文字对博主发表的内容进行总结。"
  socialNetworkId: drfeifei
  tag: ai
  type: twitter
- enableAutoReply: true
  prompt: "你现在是一名大模型领域专家，请对以下社交媒体博主的发言进行分析，并给按我指定的格式返回分析结果。\n这是你需要分析的内容：{content}\n\
    这是输出格式的说明： {{\n    \"is_relevant\": \"是否与大模型、AIGC、人工智能相关，只需要返回1或0这两个值之一即可\",\n\
    \    \"analytical_briefing\": \"分析简报\"\n}}\n其中analytical_briefing的值是一个字符串，它是针对内容所做的分析简报，仅在is_relevant为1时会返回这个值。\n\
    analytical_briefing的内容是markdown格式的，它需要符合下面的规范\n原始正文，仅当需要分析的内容不是为中文时，这部分内容才会保留，否则这部分的内容为原始的正文\n\
    翻译后的内容，仅当需要分析的内容为英文时，才会有这部分的内容。\n## Summarize\n这部分需要用非常简明扼要的文字对博主发表的内容进行总结。"
  socialNetworkId: sama
  tag: ai
  type: twitter
- enableAutoReply: true
  prompt: "你现在是一名大模型领域专家，请对以下社交媒体博主的发言进行分析，并给按我指定的格式返回分析结果。\n这是你需要分析的内容：{content}\n\
    这是输出格式的说明： {{\n    \"is_relevant\": \"是否与大模型、AIGC、人工智能相关，只需要返回1或0这两个值之一即可\",\n\
    \    \"analytical_briefing\": \"分析简报\"\n}}\n其中analytical_briefing的值是一个字符串，它是针对内容所做的分析简报，仅在is_relevant为1时会返回这个值。\n\
    analytical_briefing的内容是markdown格式的，它需要符合下面的规范\n原始正文，仅当需要分析的内容不是为中文时，这部分内容才会保留，否则这部分的内容为原始的正文\n\
    翻译后的内容，仅当需要分析的内容为英文时，才会有这部分的内容。\n## Summarize\n这部分需要用非常简明扼要的文字对博主发表的内容进行总结。"
  socialNetworkId: karpathy
  tag: ai
  type: twitter
- enableAutoReply: true
  prompt: "你现在是一名大模型领域专家，请对以下社交媒体博主的发言进行分析，并给按我指定的格式返回分析结果。\n这是你需要分析的内容：{content}\n\
    这是输出格式的说明： {{\n    \"is_relevant\": \"是否与大模型、AIGC、人工智能相关，只需要返回1或0这两个值之一即可\",\n\
    \    \"analytical_briefing\": \"分析简报\"\n}}\n其中analytical_briefing的值是一个字符串，它是针对内容所做的分析简报，仅在is_relevant为1时会返回这个值。\n\
    analytical_briefing的内容是markdown格式的，它需要符合下面的规范\n原始正文，仅当需要分析的内容不是为中文时，这部分内容才会保留，否则这部分的内容为原始的正文\n\
    翻译后的内容，仅当需要分析的内容为英文时，才会有这部分的内容。\n## Summarize\n这部分需要用非常简明扼要的文字对博主发表的内容进行总结。"
  socialNetworkId: fchollet
  tag: ai
  type: twitter
- enableAutoReply: true
  prompt: "你现在是一名大模型领域专家，请对以下社交媒体博主的发言进行分析，并给按我指定的格式返回分析结果。\n这是你需要分析的内容：{content}\n\
    这是输出格式的说明： {{\n    \"is_relevant\": \"是否与大模型、AIGC、人工智能相关，只需要返回1或0这两个值之一即可\",\n\
    \    \"analytical_briefing\": \"分析简报\"\n}}\n其中analytical_briefing的值是一个字符串，它是针对内容所做的分析简报，仅在is_relevant为1时会返回这个值。\n\
    analytical_briefing的内容是markdown格式的，它需要符合下面的规范\n原始正文，仅当需要分析的内容不是为中文时，这部分内容才会保留，否则这部分的内容为原始的正文\n\
    翻译后的内容，仅当需要分析的内容为英文时，才会有这部分的内容。\n## Summarize\n这部分需要用非常简明扼要的文字对博主发表的内容进行总结。"
  socialNetworkId: ClementDelangue
  tag: ai
  type: twitter
- enableAutoReply: true
  prompt: "你现在是一名大模型领域专家，请对以下社交媒体博主的发言进行分析，并给按我指定的格式返回分析结果。\n这是你需要分析的内容：{content}\n\
    这是输出格式的说明： {{\n    \"is_relevant\": \"是否与大模型、AIGC、人工智能相关，只需要返回1或0这两个值之一即可\",\n\
    \    \"analytical_briefing\": \"分析简报\"\n}}\n其中analytical_briefing的值是一个字符串，它是针对内容所做的分析简报，仅在is_relevant为1时会返回这个值。\n\
    analytical_briefing的内容是markdown格式的，它需要符合下面的规范\n原始正文，仅当需要分析的内容不是为中文时，这部分内容才会保留，否则这部分的内容为原始的正文\n\
    翻译后的内容，仅当需要分析的内容为英文时，才会有这部分的内容。\n## Summarize\n这部分需要用非常简明扼要的文字对博主发表的内容进行总结。"
  socialNetworkId: fi56622380
  tag: ai
  type: twitter
